spring:
  application:
    name: database-service
  datasource:
    url: jdbc:postgresql://${DATABASE}:5432/postgres
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        default_schema: project
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show-sql: true
        ddl-auto: update
    open-in-view: false
  flyway:
    enabled: true
    baseline-on-migrate: true
    validate-on-migrate: false
    table: project_schema_version
    baseline-version: 0
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

server:
  port: 8193

admin:
  email: admin@admin.com
  password: admin
